### ISSUE TITLE
Build failure on OpenBSD-current.

### ISSUE THREAD

**Issue by vext01** [nix-rust/nix#1125]
```
   Compiling nix v0.15.0 (/home/edd/source/nix)
error[E0308]: mismatched types
   --> src/sys/statfs.rs:111:9
    |
110 |     pub fn optimal_transfer_size(&self) -> i32 {
    |                                            --- expected `i32` because of return type
111 |         self.0.f_iosize
    |         ^^^^^^^^^^^^^^^ expected i32, found u32
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
111 |         self.0.f_iosize.try_into().unwrap()
    |

error[E0308]: mismatched types
   --> src/sys/statfs.rs:392:9
    |
391 |     pub fn files_free(&self) -> i64 {
    |                                 --- expected `i64` because of return type
392 |         self.0.f_ffree
    |         ^^^^^^^^^^^^^^ expected i64, found u64
help: you can convert an `u64` to `i64` and panic if the converted value wouldn't fit
    |
392 |         self.0.f_ffree.try_into().unwrap()
    |

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `nix`.
```

This is using the master branch, but the failure also exists on 0.15.0, but not on 0.14.1.

Thanks

**Comment by asomers** [comment]
This failure was probably introduced by PR #928 .  It's hard to keep the build working on OpenBSD because we don't have any CI for it.  Could you please submit a PR to fix it?

**Comment by vext01** [comment]
I can have a go.

BTW, sr.ht does OpenBSD CI and can be integrated with github.

**Comment by gigavinyl** [comment]
I'm having this issue as well still :(

**Comment by eau-u4f** [comment]
same here.

**Comment by kpcyrd** [comment]
I've asked in #cmpwn on freenode and a member of the org can add OpenBSD to the nix CI here: https://dispatch.sr.ht/

**Comment by asomers** [comment]
A better option would be if somebody could build an official OpenBSD image on GCE.  Then it could be added to Cirrus-CI.

**Comment by kpcyrd** [comment]
Sure, but getting an official image into GCE sounds like a more long-term project, using sr.ht in the meantime sounds more pragmatic instead of going without CI.

**Comment by asomers** [comment]
Just released 0.16.1, which includes the fix for this issue.
